// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCshXC4eJagQBw8N7xMWvTSQN22-XZYvZA',
    appId: '1:878915243571:web:81ee50c9a635c31c9cdd46',
    messagingSenderId: '878915243571',
    projectId: 'instaclone-jain',
    authDomain: 'instaclone-jain.firebaseapp.com',
    storageBucket: 'instaclone-jain.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAURr6IEf73LLUKPkcqKJQM-lBdOnlzzw',
    appId: '1:878915243571:android:6658eba0cea0d5ed9cdd46',
    messagingSenderId: '878915243571',
    projectId: 'instaclone-jain',
    storageBucket: 'instaclone-jain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPA3Y6Zvj7xY7NEU962gwepZfrD75byig',
    appId: '1:878915243571:ios:9d94c68147c6c51f9cdd46',
    messagingSenderId: '878915243571',
    projectId: 'instaclone-jain',
    storageBucket: 'instaclone-jain.appspot.com',
    iosBundleId: 'com.example.instaclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPA3Y6Zvj7xY7NEU962gwepZfrD75byig',
    appId: '1:878915243571:ios:8bada0c1e451a8209cdd46',
    messagingSenderId: '878915243571',
    projectId: 'instaclone-jain',
    storageBucket: 'instaclone-jain.appspot.com',
    iosBundleId: 'com.example.instaclone.RunnerTests',
  );
}
